{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ printf "%s-%s" .Release.Name "frontend" }}
  labels:
    app: frontend
spec:
  rules:
    - host: {{ .Values.ingress.hosts.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ printf "%s-%s" .Release.Name "frontend" }}
                port:
                  number: {{ .Values.service.port }}
{{- end }}
